version: "3.7"

# TODO Закрыть все внешние порты.

services:

  mongo:
    container_name: mongo
    image: "mongo:4.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - "27017:27017"

  rabbit:
    container_name: rabbit
    image: "rabbitmq:3.7-management"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"

  crawler:
    build:
      context: .
      dockerfile: cmd/crawler/Dockerfile
    image: crawler
    container_name: crawler
    restart: always
    entrypoint: /crawler
    command:
      - "--rabbit.host=rabbit"